# logging/default.yaml

version: 1
disable_existing_loggers: False

formatters:
  console_format:
    format: "%(message)s"
    datefmt: "[%X]"

  file_format:
    "()": hamilton_composer.logging.MillisecondFormatter
    format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

handlers:
  console:
    class: rich.logging.RichHandler
    level: NOTSET
    formatter: console_format
    rich_tracebacks: True
    tracebacks_extra_lines: 0
    tracebacks_code_width: 120
    tracebacks_suppress:
      - click
      - hamilton

  rotating_file:
    class: logging.handlers.RotatingFileHandler
    level: NOTSET
    formatter: file_format
    filename: run.log
    maxBytes: 10485760 # 10 MB
    backupCount: 5
    encoding: utf8

loggers: {} # NOTE: loggers are added in configure_logging

root:
  handlers: [console]
  level: WARNING
